#!/bin/bash

wget https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz -O - | \
  gunzip > /usr/share/GeoIP/GeoIP.dat.new && \
  mv -f /usr/share/GeoIP/GeoIP.dat.new /usr/share/GeoIP/GeoIP.dat && \
  cp -f /usr/share/GeoIP/GeoIP.dat /var/www/anontest/geoip

wget https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz -O - | \
  gunzip > /usr/share/GeoIP/GeoLiteCity.dat.new && \
  mv -f  /usr/share/GeoIP/GeoLiteCity.dat.new /usr/share/GeoIP/GeoLiteCity.dat && \
  cp -f /usr/share/GeoIP/GeoLiteCity.dat /var/www/anontest/geoip

/usr/bin/geoipupdate && \
  cp -f /usr/share/GeoIP/GeoIPOrg.dat /var/www/anontest/geoip && \
  cp -f /usr/share/GeoIP/GeoIPISP.dat /var/www/anontest/geoip
