#!/bin/bash
# torify
torify wget -O /var/www/tor_exitnodes.txt.new -q --user-agent="Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.1.3) Gecko/20090824 Firefox/3.5.3" https://check.torproject.org/cgi-bin/TorBulkExitList.py?ip=78.129.167.167 >> /dev/null && cp /var/www/tor_exitnodes.txt.new /var/www/tor_exitnodes.txt
