#!/bin/bash

if [ "$1" = "--install" ] ; then
  install -D -v -m 755 $0 /usr/local/bin/$(basename $0)
  exit 0
fi

PARAMS=""
VOLUMES=""
IMAGE=""
ENTRYPOINT=""
CONTAINERPARAMS=""
BUILDPARAMS=""

function entrypoint {
  ENTRYPOINT=$1
}

function container_params {
  CONTAINERPARAMS="$CONTAINERPARAMS $*"
}

function build_params {
  for i in "$@" ; do
    BUILDPARAMS="$BUILDPARAMS --build-arg $i"
  done
}

function map {
  map_from=$1
  shift
  test "$1" = "to" && shift
  mkdir -p $map_from
  map_to=$1
  VOLUMES="$VOLUMES -v $map_from:$map_to"
  echo VOLUME: $map_from:$map_to
}

function prepareImage {
  IMGNAME=$1
  shift

  if [ -d $IMGNAME ] ; then
    docker build -t $IMGNAME $@ $IMGNAME || exit 1
  else
    docker images | grep -q $IMGNAME || { docker pull $IMGNAME || exit 1 ; }
  fi
}

function depends {
  test "$1" = "on" && shift
  CONTAINER=$1
  docker ps | grep $CONTAINER || { echo Depending on $CONTAINER ; ./$CONTAINER.jd ; }
  PARAMS="$PARAMS --link $CONTAINER"
}

function port {
  echo PORT: $1
  PARAMS="$PARAMS -p $1"
}

function params {
  PARAMS="$PARAMS $@"
}

function image {
  IMAGE=$1
}

CONTNAME=$(basename $1)
CONTNAME=${CONTNAME%.*}

IMAGE=$CONTNAME

SCRIPT=$1
shift

. $SCRIPT

prepareImage $IMAGE $BUILDPARAMS

if [ -f nginx/$CONTNAME.conf ] ; then
  ln -sf $PWD/nginx/$CONTNAME.conf /etc/nginx/sites-enabled/
  CONTAINERHOSTNAME=$(grep [^$]server_name nginx/$CONTNAME.conf)
  CONTAINERHOSTNAME=${CONTAINERHOSTNAME##* }
  CONTAINERHOSTNAME=${CONTAINERHOSTNAME%;*}
  [[ "$PARAMS" == *"-h"* ]] || PARAMS="$PARAMS -h $CONTAINERHOSTNAME"
  grep -q $CONTAINERHOSTNAME certbot-domains.conf || echo "-d $CONTAINERHOSTNAME" >> certbot-domains.conf
  echo "* Please restart/reload nginx"
  echo "* Please check SSL certificates" 
fi

if docker ps -a | grep $CONTNAME
then
  docker start $CONTNAME 
else 
  echo docker run -d --name $CONTNAME $VOLUMES $PARAMS $IMAGE $ENTRYPOINT $CONTAINERPARAMS
  docker run -d --name $CONTNAME $VOLUMES $PARAMS $IMAGE $ENTRYPOINT $CONTAINERPARAMS
fi

test "$(type -t post_startup)" = "function" && post_startup
